<!DOCTYPE html>
<html lang="zxx">

<head>
    <!--====== Required meta tags ======-->
    <meta charset="utf-8" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <base href="https://gtechwebsolutions.com/">

    <!--====== Title ======-->
    <title>Privacy Policy | G Tech Solutions</title>
    <meta name="description"
        content="This Privacy Policy describes our policies and procedures on the collection, use and disclosure of your information when you respond to our advertisements" />
        <link rel="canonical" href="https://gtechwebsolutions.com/privacy-policy/" />
    <link rel="canonical" href="https://gtechwebsolutions.com/privacy-policy/" />

    <!--====== Favicon Icon ======-->
    <link rel="shortcut icon"
        href="https://dbolm29vzchgq.cloudfront.net/prod/images/wp-content/uploads/2023/05/18174527/cropped-fav-icon-32x32.png"
        type="image/x-icon">
    <!--====== Google Fonts ======-->
    <!-- <link
        href="https://fonts.googleapis.com/css2?family=Mulish:wght@400;500;600;700&family=Oswald:wght@300;400;500;600;700&display=swap"
        rel="stylesheet"> -->

    <!--====== Font Awesome ======-->
    <link rel="stylesheet" href="assets/css/font-awesome-5.9.0.css">
    <!--====== Bootstrap ======-->
    <link rel="stylesheet" href="assets/css/bootstrap.min.css">
    <!--====== Magnific Popup ======-->
    <link rel="stylesheet" href="assets/css/magnific-popup.css">
    <!--====== Falticon ======-->
    <link rel="stylesheet" href="assets/css/flaticon.css">
    <!--====== Animate ======-->
    <link rel="stylesheet" href="assets/css/animate.css">
    <!--====== Slick ======-->
    <link rel="stylesheet" href="assets/css/slick.css">
    <!--====== Main Style ======-->
    <link rel="stylesheet" href="assets/css/style.css">

    <script src="assets/css/magnific-popup.css"></script>

    <?php include('../assets/inc/header-script.php') ?>

    <style>
        @media (min-width: 576px) {
            .text-center-item .col-sm-3 {
                -ms-flex: 0 0 25%;
                flex: 0 0 25%;
                max-width: 20%;
            }
        }
    </style>

</head>

<body class="home-six">
    
    <!--body script-->
    <?php include('../assets/inc/body-script.php') ?>
    
    <!--header-->
    <!--body script-->
    <?php include('../assets/inc/header.php') ?>


    <section>
        <div class="container pt-130">
            <div class="section-title text-center mb-30">
                <h1>Privacy Policy</h1>
                <h3>G Tech Solutions</h3>
                <p style="text-align: justify;">This Privacy Policy describes our policies and procedures on the collection, use and disclosure of your information when you respond to our advertisements and tells you about Your privacy rights and how the law protects You. We use Your Personal Data to contact and support you, as well as to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
               
            </div>
        </div>

        <div class="container">
            <div class="section-title  mb-30">
                <h2>Interpretation and Definitions</h2>
                 <h3>Interpretation</h3>
                <p style="text-align: justify;">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
            </div>
            <div class="section-title  mb-30">
                <h3>Definitions</h3>
                <p style="text-align: justify;">For the purposes of this Privacy Policy:</p>
                
                <div class="pl-20">
                    <p><b>- Company</b> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to G Tech Solutions (www.gtechwebsolutions.com)</p>
                    <p><b>- Device</b> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>
                    <p><b>- Personal Data</b> is any information that relates to an identified or identifiable individual.</p>
                    <p><b>- Service</b> refers to the advertisement, website, or application.</p>
                    <p><b>- Service Provider</b> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>
                    <p><b>- Usage Data</b> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
                    <p><b>- You</b> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
                </div>
                
            </div>
            <div class="section-title  mb-30">
                <h2>Collecting and Using Your Personal Data</h2>
                <h3>Types of Data Collected</h3>
                <h4>Personal Data</h4>
                <p style="text-align: justify;">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                
                <div class="pl-20">
                    <p><b>-</b> First name and last name</p>
                     <p><b>-</b> Email address</p>
                      <p><b>-</b> Phone number</p>
                       <p><b>-</b> Location details such as your address, city, or country</p>
                        <p><b>-</b> Any other data such as personal preferences, requirements, or comments</p>
                </div>
            </div>
            <div class="section-title  mb-30">
                <h3>Use of Your Personal Data</h3>
                <p style="text-align: justify;">The Company may use Personal Data for the following purposes:</p>
                
                <div class="pl-20">
                    <p><b>- To provide and maintain our Service,</b> including to monitor the usage of our Service.</p>
                     <p><b>- To manage Your Account:</b>to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</p>
                      <p><b>- For the performance of a contract:</b>the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</p>
                       <p><b>- To contact You:</b>To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</p>
                        <p><b>- To provide You </b> with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</p>
                        <p><b>- To manage Your requests:</b>To attend and manage Your requests to Us.</p>
                        <p><b>- For business transfers:</b>We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</p>
                        <p><b>- For other purposes:</b>We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</p>
                </div>
                <p style="text-align: justify;">We may share Your personal information in the following situations:</p>
                <div class="pl-20">
                    <p><b>- With Service Providers:</b> We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</p>
                     <p><b>- For business transfers:</b>We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</p>
                      <p><b>- With Affiliates: </b>We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</p>
                       <p><b>- With business partners:</b>We may share Your information with Our business partners to offer You certain products, services or promotions.</p>
                        <p><b>- With other users: </b>when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</p>
                        <p><b>- With Your consent:</b>We may disclose Your personal information for any other purpose with Your consent.</p>
                        
                </div>
            </div>
        </div>

        <div class="container">
            <div class="section-title  mb-30">
                <h3>Retention of Your Personal Data</h3>
                <p style="text-align: justify;">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
                <p style="text-align: justify;">The Company will also retain Usage Data for internal analysis purposes.</p>

                <h3>Transfer of Your Personal Data</h3>
                <p style="text-align: justify;">Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>
                <p style="text-align: justify;">Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
                <p style="text-align: justify;">The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
                <h3>Disclosure of Your Personal Data</h3>
                <h4>Law enforcement</h4>
                <p style="text-align: justify;">Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
               <h4>Other legal requirements</h4>
                <p style="text-align: justify;">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
                
                  <div class="pl-20">
                    <p><b>-</b> Comply with a legal obligation</p>
                     <p><b>-</b> Protect and defend the rights or property of the Company</p>
                      <p><b>-</b> Prevent or investigate possible wrongdoing in connection with the Service</p>
                       <p><b>-</b> Protect the personal safety of Users of the Service or the public</p>
                        <p><b>-</b> Protect against legal liability</p>
                </div>
                
                <h3>Security of Your Personal Data</h3>
                <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>

            </div>
        </div>

        <div class="container">
            <div class="section-title  mb-30">
                <h2>Advertising</h2>
                <p style="text-align: justify;">Ads appearing on our site may be delivered to Users by advertising partners, who may set cookies. These cookies allow the ad server to recognize your computer each time they send you an online advertisement to compile non personal identification information about you or others who use your computer. This information allows ad networks to, among other things, deliver targeted advertisements that they believe will be of most interest to you. This privacy policy does not cover the use of cookies by any advertisers.</p>
            </div>
            <div class="section-title  mb-30">
                <h2>Links to Other Websites</h2>
                <p style="text-align: justify;">Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
                <p style="text-align: justify;">We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
            </div>
            <div class="section-title  mb-30">
                <h2>Changes to this Privacy Policy</h2>
                <p style="text-align: justify;">We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
                <p style="text-align: justify;">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
                <p style="text-align: justify;">This Privacy Policy was last updated on 2023/08/19 05:31:30</p>
            </div>
            <div class="section-title  mb-30">
                <h2>Contact Us</h2>
                <p style="text-align: justify;">If you have any questions about this Privacy Policy, You can contact us via email at info@gtechwebsolutions.com</p>
            </div>
            
        </div>
    </section>


   
<?php include('../assets/inc/footer.php') ?>

    </div>
    <!--End pagewrapper-->

    <!-- Scroll Top Button -->
    <button class="scroll-top scroll-to-target" data-target="html"><span class="fa fa-angle-up"></span></button>


    <!--====== Jquery ======-->
    <script src="assets/js/jquery-3.6.0.min.js"></script>
    <!--====== Bootstrap ======-->
    <script src="assets/js/bootstrap.min.js"></script>
    <!--====== Appear Js ======-->
    <script src="assets/js/appear.min.js"></script>
    <!--====== Slick ======-->
    <script src="assets/js/slick.min.js"></script>
    <!--====== Magnific Popup ======-->
    <script src="assets/js/jquery.magnific-popup.min.js"></script>
    <!--====== Isotope ======-->
    <script src="assets/js/isotope.pkgd.min.js"></script>
    <!--  WOW Animation -->
    <script src="assets/js/wow.js"></script>
    <!-- Custom script -->
    <script src="assets/js/script.js"></script>

</body>

</html>